---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallenge-be
  labels:
    app: techchallenge
spec:
  selector:
    matchLabels:
      app: techchallenge
  replicas: 2
  template:
    metadata:
      labels:
        app: techchallenge
    spec:
      containers:
        - name: techchallenge-be
          image: anified/techchallenge-be:change_LABELTAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ATMS_URL
              value: change_ATMS_URL
            - name: ATMS_HEADER_KEY
              value: change_ATMS_HEADER_KEY
            - name: ATMS_HEADER_VALUE
              value: change_ATMS_HEADER_VALUE
---
apiVersion: v1
kind: Service
metadata:
  name: techchallenge-be
spec:
  selector:
    app: techchallenge
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer