---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallenge-be
  labels:
    app: techchallenge
spec:
  selector:
    matchLabels:
      app: techchallenge
  replicas: 2
  template:
    metadata:
      labels:
        app: techchallenge
    spec:
      containers:
        - name: techchallenge-be
          image: anified/techchallenge-be:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ATMS_URL
              value: https://open-atms.airlab.aero/api/v1/
            - name: ATMS_HEADER_KEY
              value: api-key
            - name: ATMS_HEADER_VALUE
              value: G9Tw58HE6HDzyq94HFmnd2yOymAuU32k2mEgL3oTVbhLl6E1opu5Hqxb5BASwCWv
---
apiVersion: v1
kind: Service
metadata:
  name: techchallenge-be
spec:
  selector:
    app: techchallenge
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer